name: Build dex-tools

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Generate dependency graphs
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: generate

      - name: Build dex-tools with Gradle
        run: ./gradlew check distZip

      - name: Archive dex tools
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dex-tools
          path: dex-tools/build/distributions/dex-tools-*.zip
