name: Build dex-tools

on:
  push:
    branches-ignore: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build dex-tools with Gradle
        run: ./gradlew check distZip

      - name: Archive dex tools
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dex-tools
          path: dex-tools/build/distributions/dex-tools-*.zip