name: Build dex-tools and publish to Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Generate and submit dependency graphs
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: generate-and-submit

      - name: Build dex-tools with Gradle
        run: ./gradlew check -Pversion=2.4.${{ github.run_number }} distZip

      - uses: ncipollo/release-action@v1
        if: success()
        with:
          tag: 2.4.${{ github.run_number }}
          artifacts: dex-tools/build/distributions/dex-tools-*.zip

      - name: Archive dex tools
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dex-tools
          path: dex-tools/build/distributions/dex-tools-*.zip

      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}