name: Build dex-tools and publish to Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build dex-tools with Gradle
        run: ./gradlew check -Pversion=2.4.${{ github.run_number }} distZip

      - uses: ncipollo/release-action@v1
        if: success()
        with:
          tag: 2.4.${{ github.run_number }}
          artifacts: dex-tools/build/distributions/dex-tools-*.zip

      - name: Archive dex tools
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dex-tools
          path: dex-tools/build/distributions/dex-tools-*.zip

      - name: Publish to Maven Central
        run: ./gradlew -Pversion=2.4.${{ github.run_number }} publish
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}